### ISSUE TITLE
"ReAllocWarn" setting in "Media Alarms" does not take effect

### ISSUE THREAD

**Issue by nasbdh9** [JoeSchmuck/Multi-Report#39]
One of my hard drives triggered a "Re-alloc Evnt" count of 1, and then I set the ReAllocWarn value to 6, but the email still triggered the WARNING title.

**Comment by nasbdh9** [comment]
Setting the ReAllocWarn value to 6 still triggers the WARNING title and high stickiness

<img width="2150" height="904" alt="Image" src="https://github.com/user-attachments/assets/e01787f5-8940-417d-b920-5e9b7ba91e8d" />

smart info of the hdd:

```
########## NON-SMART status report for sds drive (N/A : ZL2F4KKH0000C1323M9J : No Location Data) ##########
SMARTCTL DATA

=== START OF INFORMATION SECTION ===
Vendor:               SEAGATE
Product:              ST16000NM002G
Revision:             E004
Compliance:           SPC-5
User Capacity:        16,000,900,661,248 bytes [16.0 TB]
Logical block size:   512 bytes
Physical block size:  4096 bytes
LU is fully provisioned
Rotation Rate:        7200 rpm
Form Factor:          3.5 inches
Logical Unit id:      0x5000c500cba9d34f
Serial number:        ZL2F4KKH0000C1323M9J

...

Error counter log:
           Errors Corrected by           Total   Correction     Gigabytes    Total
               ECC          rereads/    errors   algorithm      processed    uncorrected
           fast | delayed   rewrites  corrected  invocations   [10^9 bytes]  errors
read:          0        0         0         0          0     181395.677           0
write:         0        0         1         1          2      30060.501           0
verify:        0        0         0         0          0          0.022           0

Non-medium error count:        1

```

**Comment by JoeSchmuck** [comment]
Got the email.  You have found a problem, and while I wish there wasn't a problem, I appreciate you bringing it up so I can fix it.

I will be pushing out the fix in a few days, however I will send you the fix as soon as I create it tomorrow.

This issue will remain open until I push out the fix.

**Comment by JoeSchmuck** [comment]
The problem is fixed and version 3.24 is posted.  It is in your email as well.

**Comment by nasbdh9** [comment]
I noticed that the new version has the value ReAllocEvent, but it still doesn't work.

**Comment by nasbdh9** [comment]
V3.24 (25 Oct 2025) version dump email has been sent. please take a look.

**Comment by JoeSchmuck** [comment]
An updated version was emailed to you.  Please verify it works and let me know.

This issue is still open.

**Comment by JoeSchmuck** [comment]
Glad it worked.
